version: '3'
services:
  tubetweet:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongo
    command: bun --watch ./src/index.ts

  mongo:
    image: mongo:latest
    
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: